version: '3.8'

services:
  app:
    build: 
      context: .
      args:
        - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    image: deepseek-customer-service
    container_name: deepseek-service
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - REDIS_URL=redis://redis:6379/0
      - KNOWLEDGE_DIR=/app/knowledge_data
    volumes:
      - ./knowledge_data:/app/knowledge_data
    ports:
      - "8000:8000"
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    container_name: deepseek-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  nginx:
    image: nginx:alpine
    container_name: deepseek-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  redis-data: