name: ai-kefu
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn
      - openai
      - requests
      - redis
      - scikit-learn
      - numpy
